apiVersion: v1
kind: Secret
metadata:
  name: api-external
  namespace: kuadrant-system
type: kubernetes.io/tls
data:
  # Estos valores deben ser generados y codificados en base64
  # Para generar: openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes -subj "/CN=kuadrant.apps.ocp4.quitala.eu"
  # Luego: cat cert.pem | base64 -w 0 y cat key.pem | base64 -w 0
  tls.crt: <certificado en base64 codificado>
  tls.key: <clave privada en base64 codificada>

