apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: kuadrant-operatorgroup
  namespace: kuadrant-system
spec: {}

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhcl-operator
  namespace: kuadrant-system
spec:
  channel: stable
  installPlanApproval: Automatic
  name: rhcl-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: rhcl-operator.v1.1.1