apiVersion: operators.coreos.com/v1alpha1
kind: OperatorGroup
metadata:
  name: istio-operatorgroup
  namespace: istio-system
spec: {}

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator3
  namespace: istio-system
spec:
  channel: stable
  installPlanApproval: Automatic
  name: servicemeshoperator3
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: servicemeshoperator3.v3.1.3