apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-simple-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sgutierr/demorhcl.git
    targetRevision: HEAD
    path: installation
    directory:
      include: istio-namespace.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: test-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

