apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-rbac
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/sgutierr/demorhcl.git
    targetRevision: HEAD
    path: argocd/manifests
    directory:
      include: argocd-rbac.yaml
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

