apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: connectivity-link-operators
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/sgutierr/demorhcl.git  # Actualizar con tu repositorio
    targetRevision: HEAD
    path: installation
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators
  dependsOn:
    - operators-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

