apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operators-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sgutierr/demorhcl.git  # Actualizar con tu repositorio
    targetRevision: HEAD
    path: installation
    directory:
      include: istio-namespace.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

