apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tls-secret
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/sgutierr/demorhcl.git  # Actualizar con tu repositorio
    targetRevision: HEAD
    path: argocd/manifests
    directory:
      include: tls-secret.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kuadrant-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  dependsOn:
    - operators-system

